name: sensei-meta
dependencies:
  - base >= 4.7 && < 5
  - base-compat >= 0.8
  - process
  - fsnotify
  - time
  - wai
  - warp
  - http-types
  - stm
  - text
  - network
  - ansi-terminal
  - directory
  - http-client
  - bytestring
  - filepath
  - unix

ghc-options: -Wall

library:
  source-dirs:
    - src
    - doctest/ghci-wrapper/src/

executables:
  sensei-meta:
    main: driver/Main.hs
    dependencies:
      - sensei-meta

  sensei-web-meta:
    main: driver/Web.hs
    dependencies:
      - sensei-meta

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - sensei-meta
      - hspec == 2.*
      - hspec-wai
      - mockery
      - silently
      - interpolate
