name: sensei
dependencies:
  - base >= 4.7 && < 5
  - base-compat >= 0.8
  - process
  - fsnotify
  - time
  - wai
  - warp
  - http-types
  - stm
  - text
  - network
  - ansi-terminal
  - directory
  - http-client
  - bytestring
  - filepath
  - unix

ghc-options: -Wall

library:
  source-dirs:
    - src
    - doctest/ghci-wrapper/src/

executables:
  sensei:
    main: driver/Main.hs
    dependencies:
      - sensei

  sensei-web:
    main: driver/Web.hs
    dependencies:
      - sensei

  seito:
    main: driver/Client.hs
    dependencies:
      - sensei

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - sensei
      - hspec >= 2.2.1
      - hspec-wai
      - mockery
      - silently
      - interpolate
